# Autogenerated wrapper script for nPth_jll for aarch64-apple-darwin
export libnpth

JLLWrappers.@generate_wrapper_header("nPth")
JLLWrappers.@declare_library_product(libnpth, "@rpath/libnpth.0.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libnpth,
        "lib/libnpth.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
